services:
  assinatura-med:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
      - USERS_FILE=/app/data/users.json
    volumes:
      - logs_data:/app/logs
      - users_data:/app/data
    restart: unless-stopped

volumes:
  logs_data:
  users_data:
